version: '3'

services:
    laravel.test:
        container_name: laravel.test
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "SqlServer2019!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        ports:
        - "1433:1433"
        networks:
            - sail
    mssqltools:
        image: mcr.microsoft.com/mssql-tools
        depends_on:
        - sqlserver
        volumes:
        - ./docker/sqlserver/01.sql:/tmp/01.sql
        - ./docker/sqlserver/init.sh:/tmp/init.sh
        command: /bin/bash ./tmp/init.sh
        networks:
            - sail

    pgsql:
        image: 'postgres:15'
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: 'x'
            POSTGRES_DB: 'laravel'
            POSTGRES_USER: 'laravel'
            POSTGRES_PASSWORD: 'x'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge
volumes:
    sail-sqlserver:
        driver: local
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
